/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-11-16 01:10:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Registration.css\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<pre></pre>\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h1>Register</h1>\r\n");
      out.write("    <p>Please fill in this form to create an account.</p>\r\n");
      out.write("    <hr>\r\n");
      out.write(" \t<label for=\"email\"><b>FirstName</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter FirstName\" name=\"fname\" required>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"email\"><b>MiddleName</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter MiddleName\" name=\"mname\" >\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"email\"><b>LastName</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter LastName\" name=\"lname\" required>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"email\"><b>Gender</b></label>\r\n");
      out.write("  <hr>\r\n");
      out.write("    <input type=\"radio\" name=\"gender\" value=\"male\"> Male<br><input type=\"radio\" name=\"gender\" value=\"female\"> Female<br>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <label>DOB</label>\r\n");
      out.write("\t<input type=\"date\">   \r\n");
      out.write("    <hr>\r\n");
      out.write("    <label>Address</label><hr>\r\n");
      out.write("    <textarea style=\"align:left-center\" rows=\"4\" cols=\"50\">\r\n");
      out.write("\tEnter Your address here\r\n");
      out.write("\t</textarea>\r\n");
      out.write("    <hr>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"email\"><b>Father's Name </b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Father's Name\" name=\"faname\" required>\r\n");
      out.write("    <hr>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"email\"><b>Occupation Type </b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Occupation Type\" name=\"otaname\" required>\r\n");
      out.write("    <hr>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"email\"><b>Email</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Email\" name=\"email\" required>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"psw\"><b>Password</b></label>\r\n");
      out.write("    <input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" required>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"psw-repeat\"><b>Repeat Password</b></label>\r\n");
      out.write("    <input type=\"password\" placeholder=\"Repeat Password\" name=\"psw-repeat\" required>\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("    <p>By creating an account you agree to our <a href=\"#\">Terms & Privacy</a>.</p>\r\n");
      out.write("    <button type=\"submit\" class=\"registerbtn\">Register</button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container signin\">\r\n");
      out.write("    <p>Already have an account? <a href=\"#\">Sign in</a>.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
