/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-11-23 06:27:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Register.css\">\r\n");
      out.write("    <title>Registration Form</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"yellow-square\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form  action=\"/FinalBankingProject/register\" method=\"POST\">\r\n");
      out.write("            <h1 align=\"center\">Registration Form</h1>\r\n");
      out.write("            <table align=\"center\" cellpadding=\"15\" >\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <b>Enter FirstName:</b>\r\n");
      out.write("                        <td><input type=\"text\" placeholder=\"FirstName\" name=\"firstname\" size=\"20\" required><br></td>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <b>Enter MiddleName:</b>\r\n");
      out.write("                        <td><input type=\"text\" placeholder=\"MiddleName\" name=\"middlename\" size=\"20\"><br></td>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <b>Enter LastName:</b>\r\n");
      out.write("                        <td><input type=\"text\" placeholder=\"LastName\" name=\"lastname\" size=\"20\" required><br></td>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <td>\r\n");
      out.write("                    <b>Date-Of-Birth :</b>\r\n");
      out.write("                    <td><input type=\"date\" name=\"dateofbirth\" size=\"20\" required><br></td>\r\n");
      out.write("                </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <b>Gender:</b>\r\n");
      out.write("                        <td><input type=\"radio\" name=\"gender\" value=\"Male\" size=\"20\">Male\r\n");
      out.write("                            <input type=\"radio\" name=\"gender\" value=\"Female\" size=\"20\">Female<br></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <b>Address:</b>\r\n");
      out.write("                        <td> <textarea rows=\"5\" cols=\"30\" name=\"address\" size=\"20\" placeholder=\"Enter your Address here\">\r\n");
      out.write("                 </textarea>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        State :\r\n");
      out.write("                        <td><select>\r\n");
      out.write("                        <option value=\"Maharashtra\"  name=\"state\">Maharashtra</option>\r\n");
      out.write("                        <option value=\"Delhi\" name=\"state\" >Delhi</option>\r\n");
      out.write("                        <option value=\"Andhra Pradesh\"  name=\"state\">Andhra Pradesh</option>\r\n");
      out.write("                        <option value=\"Assam\" name=\"state\">Assam</option>\r\n");
      out.write("                        <option value=\"Goa\" name=\"state\">Goa</option>\r\n");
      out.write("                    </select></td><br></td>\r\n");
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        ZipCode:\r\n");
      out.write("                        <td><input type=\"number\" placeholder=\"Enter Pincode\" name=\"zipcode\" size=\"20\" required><br></td>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>FathersName:\r\n");
      out.write("                        <td> <input type=\"text\" placeholder=\"Enter FatherName\" name=\"fathername\" size=\"20\" required></td><br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>OccupationType:\r\n");
      out.write("                        <td> <input type=\"text\" placeholder=\"Enter OccupationType\" name=\"occType\" size=\"20\" required></td><br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Income:\r\n");
      out.write("                        <td> <input type=\"number\" placeholder=\"Enter Income\" name=\"income\" size=\"20\" required></td><br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>AdharCard Number:\r\n");
      out.write("                        <td><input type=\"text\" placeholder=\"Enter AdharCard Number\" name=\"aadhar\" size=\"20\" required></td><br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Email Id:\r\n");
      out.write("                        <td> <input type=\"email\" placeholder=\"Enter EmailId\" name=\"emailId\" size=\"20\" required></td><br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <td>Password:\r\n");
      out.write("                    <td> <input type=\"password\" placeholder=\"Enter Password\" name=\"password\" size=\"20\" required></td><br>\r\n");
      out.write("                </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Mobile Number:\r\n");
      out.write("                        <td><input type=\"number\" placeholder=\"Enter MobileNumber\" name=\"mobileNo\" size=\"20\" required></td><br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td align=\"center\"><button class=\"button\">Submit</button>\r\n");
      out.write("                        <!-- <button class=\"button\" type=\"reset\" style=\"float:left\" value=\"Reset\">Reset</button> -->\r\n");
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
